---
###any yaml file start with three dash
-
  hosts: all 
#yaml follow the format of python this - list of items
  #target where you want to run your play book 
  #varaible : it is used for resusing the playbook
  vars:
    motd_redhat: "Welcome to Redhat System-rock\n"
    motd_ubuntu: "Welcome to ubuntu\n"
    #tomcat maven 
  #task: the list of task that are going to execute
  #handlers: handler will execute only if there is any change in the task 
  tasks:
  ##inside task you can define list 
     
      - name: create a user johnd 
        ansible.builtin.user:
          name: johnd
      - name: create users with loop
        user:
          name: '{{ item.name }}' #two variable
          uid: '{{ item.uid }}'
          state: present
          #in place of loop keyword you can use with_items both will give you same result
        with_items:
            - name: tom
              uid: 1020
            - name: harry
              uid: 1030
            - name: jerry
              uid: 1040
               
          ###this is duplication or i can say repeation
          #this is an standard loop
    